### ISSUE TITLE
Publish odelay to Maven Central

### ISSUE THREAD

**Issue by franklinhu** [softprops/odelay#11]
I'm trying to use a library that depends on undelay, which transitively depends on this project. Was wondering if you could publish 0.1.0 to Maven Central so maven resolves everything correctly?

Thanks!

**Comment by jozic** [comment]
+1 
this would be nice

**Comment by jozic** [comment]
hey @softprops 
any progress here?

**Comment by softprops** [comment]
published as a minor release 0.1.1 because sonatype required some extra pom metadata and bintray wouldn't let me publish over top of 0.1.0. Sonatype should sync up with maven central soon
